backend:
  name: github
  repo: emmajgrimes/headforwards-website

media_folder: static/img
public_folder: /img

collections:
  - label: "Design Pages"
    name: "design-pages"
    widget: "list"
    folder: "src/pages/design-pages"
    fields:
      - label: "Page Title"
        name: "title"
        widget: "text"
      - label: "Page Components"
        name: "components"
        widget: "list"
        types:
          - label: "Carousel"
            name: "carousel"
            widget: object
            fields:
                - {label: Header, name: header, widget: string, default: "Image Gallery"}
                - {label: Template, name: template, widget: string, default: "carousel.html"}
                - label: Images
                  name: images
                  widget: list
                  field: {label: Image, name: image, widget: image}
          - label: "Spotlight"
            name: "spotlight"
            widget: object
            fields:
              - {label: Header, name: header, widget: string, default: "Spotlight"}
              - {label: Template, name: template, widget: string, default: "spotlight.html"}
              - {label: Text, name: text, widget: text, default: "Hello World"}
      - label: "Page Footer"
        name: "footer"
        widget: "markdown"
