backend:
  name: github
  repo: emmajgrimes/headforwards-website

media_folder: static/img
public_folder: /img

collections:
  - label: "Design Pages"
    name: "design-pages"
    widget: "list"
    folder: "src/pages/design-pages"
    create: true
    identifier_field: title
    fields:
      - {label: "Template Key", name: "templateKey", widget: "hidden", default: "design-page"}
      - {label: "Page Title", name: "title", widget: "text"}
      - label: "Page Components"
        name: "components"
        widget: "list"
        types:
          - label: "Heading Component"
            name: "heading"
            description: "Header and paragraph"
            widget: object
            fields:
              - {label: Heading, name: heading, widget: string}
              - {label: Description, name: description, widget: markdown}
              - {label: "Two Columns", name: "twoColumns", widget: "boolean", default: true}
          - label: "Another Component"
            name: "anotherComponent"
            widget: object
            fields:
              - {label: text, name: text, widget: markdown}
